(ns todo.labels)

(def store-file "todos.dat")

(def start-message "Welcome to TODO list app in Clojure made by Patrik Valkovic")
(def end-message "Thank you for using TODO list")
(def your-choice "Your choice:")
(def wrong-entry "Wrong entry")
(def your-todos "Your TODOs:")
(def what-to-done "Which TODO you want mark as done:")
(def write-name "Write label for new todo:")
(def what-to-delete "Which one you want to delete:")
(def press-enter-to-continue "Press enter to continue")
(def what-to-edit "Which one you want to edit:")
(def default "default")
(def ask-for-label "New label")
(def ask-for-done "Is it done?")